GET http://localhost:5050/api/article
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2QxODcxZjFhNmRkMWNkMTVjNzNiNDUiLCJpYXQiOjE3NDE3ODg2ODQsImV4cCI6MTc0MTc5MjI4NH0.nLwKOOCQHgIGj6srtvO5sUQRifdZ3XFyFYYko82Jv48

